### ISSUE TITLE
Solve branch coverage issues on Jest/Coveralls

### ISSUE THREAD

**Issue by lucianoratamero** [labcodes/rel-events#1]
For some unknown reason (at least to me), even though I've added tests for every single scenario and branching paths, there are still two lines of code that jest/coveralls say they're not covered; both of them are the lines for the initialization of Event and RequestEvent classes.

It made me lower the branch coverage goal to 95%, which is not ideal. :(

**Comment by isabarros** [comment]
Fixed on https://github.com/labcodes/rel-events/pull/9 :)
