### ISSUE TITLE
Add check to throw error if an Event/HTTPEvent is initialized without args

### ISSUE THREAD

**Issue by lucianoratamero** [labcodes/rel-events#10]
As suggested by @isabarros :
"(Currently) The error thrown in both scenarios is 'An Event should be initialized with an event name.' which is the first check done in the constructor, you might probably want to add another check prior to that to see if it falls in the empty scenario and throw something like 'An Event should not be initialized without parameters.'

**Comment by objNameGit** [comment]
i`m sorry. I'm not sure I get it.
You need to add a check to r'el-events/lib/events.js ' that the constructor did not pass the arguments?

**Comment by isabarros** [comment]
@objNameGit The idea is to throw an error 'An Event should not be initialized without parameters.' in case the constructor is called without arguments.

**Comment by objNameGit** [comment]
okey. can i take this task?

**Comment by isabarros** [comment]
unless @lucianoratamero is already working on that you can go for it! :)

**Comment by lucianoratamero** [comment]
sure thing, go ahead! just remember to add the tests for it, @objNameGit , and thanks for contributing <3

**Comment by lucianoratamero** [comment]
fixed on #11
