### ISSUE TITLE
Revert global threshold for branch code coverage to 100

### ISSUE THREAD

**Issue by lucianoratamero** [labcodes/rel-events#12]
Since @isabarros has fixed the issue with the branching tests, we can now revert the threshold of branch coverage to 100 again.

To do that, we just need to change the settings inside the package.json file from 95 to 100 and run the tests. If everything goes well, just send the PR to be accepted.

Thanks!

**Comment by PoojaKhandhadia** [comment]
I will work on it :)

**Comment by lucianoratamero** [comment]
fixed by #15
